# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1 #default replica count for standalone=1 & ha=3

standalone:      #Creates standalone deployment
  enabled: false
ha:              #Creates HA statefulset
  enabled: false

#############################IMAGE SECTION#########################################

image:
  repository: mongo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

############################HA STATEFULSET SECTION################################

statefulset:
  name: mongod                  #Statefulset name
  volume: 20Gi                  #PVC Volume size
  secrets:
    name: secrets               #Secret Name
    username: admin             #DB User Name
    password: admin             #DB Password
  service:
    name: mongodb-service       #headless Service Name
    port: 27017                 #headles service Port
    type: ClusterIP             #headless service type

###########################MAYASTOR VOLUME REPLICA SECTION############################################

  singlereplica:                      # Single replica mayastor Volume
    scname:                 # Single replica sc name
  multireplica:                       # Multi replicas mayastor Volume
    enabled: false
    scname:                 #Three replica sc name

#############################################MONGO CLIENT SECTION####################################

mongoclient:
  name: mongo-client            #Mongo Client deployment name
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
#############################################YCSB SECTION########################################

ycsb:
  name: ycsb
  image:
    repository: thulaseebyt
    name: ycsb
    pullPolicy: IfNotPresent
    tag: "latest"

###########################################STANDALONE STORAGE SECTION######################################
    
storage:                        #Storage section for standalone
  pvcname: mongo-data           # PVC name
  size: 20Gi                    #pvc size
  accessmode: ReadWriteOnce
########################################STANDALONE SECRETS SECTION############################################

secrets:
  name: mongo-creds
  username: admin
  password: admin123

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 27017

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
