apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: openebs-cstor-replicated
