{{- if .Values.ha.enabled }}
apiVersion: v1
data:
  password: {{ .Values.statefulset.secrets.password | b64enc | quote }}
  username: {{ .Values.statefulset.secrets.username | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.statefulset.secrets.name }}
type: Opaque
{{- end }}
