apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ycsb.name }}
  labels:
    app: {{ .Values.ycsb.name }}
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ycsb.name }}
      role: client
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.ycsb.name }}
        role: client
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ycsb.image.repository }}/{{ .Values.ycsb.image.name }}:{{ .Values.ycsb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "3650d"]
