---
apiVersion: v1
kind: Pod
metadata:
  name: @podname@
  labels:
    app: @testid@
spec:
  restartPolicy: Never
  @nodeSelector@:
    type: worker
  containers:
  - command:
    - sh
    - -c
    - 'fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file1 --ioengine=libaio --readwrite=randread --runtime=60s --time_based --ramp_time=2s --size=3G --name=test --numjobs=8 --direct=1 --iodepth=2 --group_reporting > /tmp/fiotest; exit 0;'
    image: ljishen/fio
    name: fioload
    volumeMounts:
    - mountPath: /mnt
      name: data-volume
  - command: ["/bin/sh", "-c"]
    args:
      - cnt=0;
        while [ $cnt -ne 1 ];
        do
          sleep 5;
          cnt=`ls -ltr /mnt/file1 2>/dev/null | wc -l`;
        done;
        sleep 5;
        fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file2 --ioengine=libaio --readwrite=randread --runtime=15s --time_based --ramp_time=2s --size=3G --name=test --direct=1 --group_reporting > /fio-results/@output@;
        exit 0;
    image: ljishen/fio
    name: fio
    volumeMounts:
    - mountPath: /fio-results
      name: results-volume
    - mountPath: /mnt
      name: data-volume
  volumes:
  - name: results-volume
    hostPath:
      path: /tmp/fio-results/@testid@
      type: DirectoryOrCreate
  - name: data-volume
    persistentVolumeClaim:
      claimName: @pvc@
