---
apiVersion: v1
kind: Pod
metadata:
  name: @podname@
  labels:
    app: @testid@
spec:
  restartPolicy: Never
  @nodeSelector@:
    type: worker
  containers:
  - command:
    - sh
    - -c
    - 'fio --blocksize=@bs@ --verify=0 --randrepeat=0 --filename=/mnt/file1 --ioengine=libaio --readwrite=randread --runtime=15s --time_based --ramp_time=2s --size=3G --name=test --numjobs=8 --direct=1 --iodepth=2 --group_reporting > /fio-results/@output@; exit 0;'
    image: ljishen/fio
    name: fioload
    volumeMounts:
    - mountPath: /fio-results
      name: results-volume
    - mountPath: /mnt
      name: data-volume
  volumes:
  - name: results-volume
    hostPath:
      path: @results_dir@/@testid@
      type: DirectoryOrCreate
  - name: data-volume
    persistentVolumeClaim:
      claimName: @pvc@
